### ISSUE TITLE
Harden the allow list

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-registry#13]
The snaps-registry contains:
* TypeScript types
* Blocklist data
* Allowlist data
  * Snap metadata like user readable names

At least the allowlist data has to be hardened, only the `@metamask/npm-publishers` team should be able to deploy new versions of the allowlist.

We need to figure out a way how to secure those deployments and then implement.

One possible venue is having a separate production branch, similar how the `gh-pages` branch is hardened.

Additional info: https://app.zenhub.com/workspaces/snaps-615b3a7c08d2b20015eb6c4e/issues/gh/metamask/snaps-registry/14

**Comment by Mrtenz** [comment]
Since the registry is just a JSON file, and we fetch it over the internet, it could be included in the `gh-pages` branch. That prevents the need for another branch.
