### ISSUE TITLE
[Update Snap] Solana Wallet

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps-registry#140]
## Checklist

All items in the list below needs to be satisfied.

- [x] Is the summary of the change documented in this ticket?
- [x] Has a MetaMask Snaps team member reviewed whether the changes need to be vetted?
- [x] If there are changes that need to be vetted, attach a description and the relevant fixes/remediations to this issue.
- [ ] The corresponding pull request in this repo has been merged.

**Comment by Montoya** [comment]
This update solely comprises metadata update in `package.json` and `snap.manifest.json`: https://github.com/solflare-wallet/solflare-snap/commit/2d3a817bc04d13dfebaa2b3c7529eaf6e264dbe2

**Comment by ohire2** [comment]
I removed my Solana wallet from my metamask and re-added. It gave me another wallet address with zero funds. The other wallet had funds in it. Please help how do i recover the other original wallet.
