### ISSUE TITLE
[New Snap] Polkadot Wallet

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps-registry#143]
## Checklist

All items in the list below needs to be satisfied.

- [x] Is the Snap repository publicly accessible and linked in this ticket? https://github.com/ChainSafe/metamask-snap-polkadot
- [x] Is the Snap distributed on [npm](https://www.npmjs.com/) and linked in this ticket? https://www.npmjs.com/package/@chainsafe/polkadot-snap
- [x] Has an audit been performed and the audit report attached or linked in this issue? https://sayfer.io/audits/metamask-snap-audit-report-for-polkadot/
- [x] Is a complete list of discovered vulnerabilities from the audit documented in this issue?
- [x] For vulnerabilities that have been deemed necessary to be addressed, are the links to the fixes attached to this issue?
- [x] For vulnerabilities that have been deemed not necessary to be addressed, is a reason for each of them documented in this issue?
- [ ] The corresponding pull request in this repo has been merged.

**Comment by Montoya** [comment]
This is pending version 0.6.0 being published on npm

**Comment by danforbes** [comment]
@Montoya are you referring to the version of the Polkadot Wallet snap? According to NPM that is on version 0.7.5 https://www.npmjs.com/package/@chainsafe/polkadot-snap

**Comment by Montoya** [comment]
@danforbes I don't know why I couldn't find that before but that's great. I will point out a couple things: 

- The README says that Snaps are only supported in Flask
- In the `snap.manifest.json` file it looks like there is no icon specified

**Comment by Montoya** [comment]
The version to allowlist is 0.7.7: https://www.npmjs.com/package/@chainsafe/polkadot-snap

This issue should document the audit findings, fixes, and any changes made since the audited version.

**Comment by Montoya** [comment]
There are two findings in the audit report: 

### 1. RPC URLs are defined as wsRpcUrl while using HTTP

This is a fair callout, but as long as the Snap functions with HTTP, it is not an issue. It does not need to be fixed. 

### 2. Confirmations [sic] for Key Features are not Handled When Rejected

This finding is not relevant. The way Snap execution works, the Snap lifecycle terminates as soon as execution stops. Therefore, it is not necessary to handle an "else" that will just return or terminate execution. The control flow of the Snap source code is sufficient as implemented. No change has to be made. 

The rest of the findings in the audit report are Low or Informational and do not need to be addressed.
