### ISSUE TITLE
[New Snap] Filecoin

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps-registry#221]
## Checklist

All items in the list below needs to be satisfied.

- [x] Is the Snap repository publicly accessible and linked in this ticket? https://github.com/filecoin-project/filsnap
- [x] Is the Snap distributed on [npm](https://www.npmjs.com/) and linked in this ticket? https://www.npmjs.com/package/filsnap
- [x] Has an audit been performed and the audit report attached or linked in this issue? https://consensys.io/diligence/audits/2023/08/metamask/partner-snaps-filsnap/
- [x] Is a complete list of discovered vulnerabilities from the audit documented in this issue?
- [x] For vulnerabilities that have been deemed necessary to be addressed, are the links to the fixes attached to this issue?
- [x] For vulnerabilities that have been deemed not necessary to be addressed, is a reason for each of them documented in this issue?
- [ ] The corresponding pull request in this repo has been merged.

**Comment by bowensanders** [comment]
**List of Vulnerabilities:** 
_(Links to audit report with links to fix commits)_

[• Markdown and Control Character Injection - Critical ](https://consensys.io/diligence/audits/2023/08/metamask/partner-snaps-filsnap/#markdown-and-control-character-injection) - Fixed
[• Directly Exposed Private Key Export - Critical ](https://consensys.io/diligence/audits/2023/08/metamask/partner-snaps-filsnap/#directly-exposed-private-key-export) - Fixed
[• fil_configure Allows Anyone to Change the Snap’s Configuration - Major ](https://consensys.io/diligence/audits/2023/08/metamask/partner-snaps-filsnap/#fil_configure-allows-anyone-to-change-the-snaps-configuration) -  Partially Addressed
[• Lack of Signature Dialog Context and RPC Origin - Major ](https://consensys.io/diligence/audits/2023/08/metamask/partner-snaps-filsnap/#lack-of-signature-dialog-context-and-rpc-origin) - Fixed
[• Missing Address Protection - Medium ](https://consensys.io/diligence/audits/2023/08/metamask/partner-snaps-filsnap/#missing-address-protection) - Fixed
[• Missing Timeout in RPC.call - Medium ](https://consensys.io/diligence/audits/2023/08/metamask/partner-snaps-filsnap/#missing-timeout-in-rpccall) - Fixed
[• Unnecessary Distribution of Private Key Information - Minor ](https://consensys.io/diligence/audits/2023/08/metamask/partner-snaps-filsnap/#unnecessary-distribution-of-private-key-information) - Fixed
