### ISSUE TITLE
[Update Snap] Casper Manager 1.0.4

### ISSUE THREAD

**Issue by KillianH** [MetaMask/snaps-registry#252]
## Checklist

All items in the list below needs to be satisfied.

- [X] Is the summary of the change documented in this ticket?
- [x] Has a MetaMask Snaps team member reviewed whether the changes need to be vetted?
- [x] If there are changes that need to be vetted, attach a description and the relevant fixes/remediations to this issue.
- [ ] The corresponding pull request in this repo has been merged.

**Comment by KillianH** [comment]
Here's the git diff : https://github.com/casper-ecosystem/casper-manager/compare/1.0.3...1.0.4

Main changes to the snap : 
- Changed logo
- Added request origins on dialogs
- Added Signing key on the Sign message dialog
- Refactored a variable name

Other changes : 
- Added FAQ / Knowledge base
- Updated the CI/CD

**Comment by Montoya** [comment]
LGTM
