### ISSUE TITLE
Request for Adding License Information to @metamask/snaps-registry on npm

### ISSUE THREAD

**Issue by JOHNBASS** [MetaMask/snaps-registry#295]
We are currently developing a snap and preparing to go live. However, we have encountered an issue with the @metamask/snaps-registry package on npm, as it lacks license information. This omission is causing our code information security scans to fail.

We kindly request your assistance in updating a version of @metamask/snaps-registry on the npm registry that includes the necessary license information. Your help in resolving this matter is greatly appreciated.

Thank you very much for your assistance.

Best regards,
John.

**Comment by FrederikBolding** [comment]
Hi @JOHNBASS - I will make sure we cut a release with the new licensing information. Will update this issue once that is done!

**Comment by FrederikBolding** [comment]
@JOHNBASS I just published version `2.1.1` which as LICENSE information included.
