### ISSUE TITLE
[New Snap] Galactica ZK Vault

### ISSUE THREAD

**Issue by zwilling** [MetaMask/snaps-registry#320]
## Checklist

All items in the list below needs to be satisfied.

- [x] Is the Snap repository publicly accessible and linked in this ticket? https://github.com/Galactica-corp/galactica-monorepo/tree/main/packages/snap 
- [x] Is the Snap distributed on [npm](https://www.npmjs.com/) and linked in this ticket?  https://www.npmjs.com/package/@galactica-net/snap?activeTab=code
- [x] Has an audit been performed and the audit report attached or linked in this issue? https://sayfer.io/audits/metamask-snap-audit-report-for-galactica/
- [x] Is a complete list of discovered vulnerabilities from the audit documented in this issue?
- [x] For vulnerabilities that have been deemed necessary to be addressed, are the links to the fixes attached to this issue?
- [x] For vulnerabilities that have been deemed not necessary to be addressed, is a reason for each of them documented in this issue?
- [ ] The corresponding pull request in this repo has been merged.

**Comment by zwilling** [comment]
List of discovered vulnerabilities:

1. SAY-01 [Medium] | Non-functional Demo Samples | Resolved in 
  -  https://github.com/Galactica-corp/galactica-monorepo/commit/931ed3a8f95b5c610d497dece6e9d1dcea764c2a
  - https://github.com/Galactica-corp/galactica-monorepo/commit/cd5faa555f17bacb437a2b8594e2edfd65530214#diff-9b214ce1f653323695d43c788e7d124417eb2fb858265b1a85189d3363993bbb
2. SAY-02 [Low] | Unused Functions | Resolved in  
  -  https://github.com/Galactica-corp/galactica-monorepo/commit/db77ea1a7ef55029101d30b0b7c1f7fb2b4ca97c
3. SAY-03 [Low] | Commented Code and Leftover TODOs | Resolved in  
  -  https://github.com/Galactica-corp/galactica-monorepo/commit/74b383875ada91ae1056ab0f91255999ec582396
  - https://github.com/Galactica-corp/galactica-monorepo/commit/2d59128f1b67d8f7325b471046254f03ec972593
4. SAY-04 [Informational] | Missing URL Validation | Resolved in 
  - https://github.com/Galactica-corp/galactica-monorepo/commit/90d4dc628453c7d66f1dc819f9f33102f5624153
  - https://github.com/Galactica-corp/galactica-monorepo/commit/1dde61921130bd256226e1858745ec9bdc90f9a6

**Comment by Montoya** [comment]
Hi, I will be taking this to a new PR to get merged. In the meantime, the Galactica site needs to be updated to no longer require Flask: https://app-andromeda.galactica.com/ 

Otherwise it will not work with the Snap when it is added to our allowlist for stable.

**Comment by zwilling** [comment]
Thanks for processing the PR.
I am in contact with the front-end team and will notify you when the website works with the stable version of Metamask.

**Comment by zwilling** [comment]
The [website](https://app-andromeda.galactica.com/) now allows the user to continue with the stable version of Metamask.
