### ISSUE TITLE
[New Snap] AMAX UP

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps-registry#330]
## Checklist

All items in the list below needs to be satisfied.

- [x] Is the Snap repository publicly accessible and linked in this ticket? https://github.com/armoniax/amaxup.evmsnap
- [x] Is the Snap distributed on [npm](https://www.npmjs.com/) and linked in this ticket? https://www.npmjs.com/package/@amax/amaxsnap
- [x] Has an audit been performed and the audit report attached or linked in this issue? https://sayfer.io/audits/metamask-snap-audit-report-for-amax
- [x] Is a complete list of discovered vulnerabilities from the audit documented in this issue?
- [x] For vulnerabilities that have been deemed necessary to be addressed, are the links to the fixes attached to this issue?
- [x] For vulnerabilities that have been deemed not necessary to be addressed, is a reason for each of them documented in this issue?
- [ ] The corresponding pull request in this repo has been merged.

**Comment by Narsiss** [comment]
Hello, we've fixed following problems in this [commit](https://github.com/armoniax/amaxup.evmsnap/commit/bfd016ab3affa0b39ec549ebaaccbfb73bcb562e)
![Screenshot 2023-12-12 at 22 37 08](https://github.com/MetaMask/snaps-registry/assets/5062214/71bb1ec7-22ea-4d39-8ae6-7d39b01c39b3)

**Comment by Montoya** [comment]
List of discovered vulnerabilities: 

- SAY-01 Uninformative Confirmation Popup - Fixed in https://github.com/armoniax/amaxup.evmsnap/commit/4f03e8417136be066229463f52a926b170f9e491
- SAY-02 Dependencies with Known Vulnerabilities - Acknowledged _This is classified as low, these are sub-dependencies, and there is no clear indication that they affect the Snap_
- SAY-03 Type Checking Is not Uniform - Fixed in https://github.com/armoniax/amaxup.evmsnap/commit/4f03e8417136be066229463f52a926b170f9e491
- SAY-04 Insufficient Test Coverage - Fixed in https://github.com/armoniax/amaxup.evmsnap/commit/4f03e8417136be066229463f52a926b170f9e491

The remaining findings are informational and not required to be listed here. 

The version to be allowlisted is
