### ISSUE TITLE
[New Snap] MultiverseX

### ISSUE THREAD

**Issue by khanti42** [MetaMask/snaps-registry#691]
## Checklist

All items in the list below needs to be satisfied.

- [x] Is the Snap repository publicly accessible and linked in this ticket?
- [x] Is the Snap distributed on [npm](https://www.npmjs.com/) and linked in this ticket?
- [x] Has an audit been performed and the audit report attached or linked in this issue?
- [x] Is a complete list of discovered vulnerabilities from the audit documented in this issue?
- [x] For vulnerabilities that have been deemed necessary to be addressed, are the links to the fixes attached to this issue?
- [x] For vulnerabilities that have been deemed not necessary to be addressed, is a reason for each of them documented in this issue?
- [ ] The corresponding pull request in this repo has been merged.

**Comment by khanti42** [comment]
GitHub : https://github.com/multiversx/mx-metamask-snaps
Npm : https://www.npmjs.com/package/@multiversx/metamask-snap
Audit : https://wp.hacken.io/wp-content/uploads/2024/06/Final_Report_Hacken_Multiverse-X_dApp_May_2024.pdf

**Comment by khanti42** [comment]
Note : https://multiversx.com/metamask, snap website will be live on Monday. It's already present in the linked PR.

**Comment by Montoya** [comment]
The audit findings are categorized as "low" and do not need to be documented or mitigated.
