### ISSUE TITLE
[New Snap] Qtum Wallet

### ISSUE THREAD

**Issue by khanti42** [MetaMask/snaps-registry#773]
## Checklist

All items in the list below needs to be satisfied.

- [x] Is the Snap repository publicly accessible and linked in this ticket: https://github.com/qtumproject/qtum-extension-wallet
- [x] Is the Snap distributed on [npm](https://www.npmjs.com/) and linked in this ticket: https://www.npmjs.com/package/@qtumproject/qtum-wallet
- [x] Has an audit been performed and the audit report attached or linked in this issue?
- [x] Is a complete list of discovered vulnerabilities from the audit documented in this issue?
- [ ] For vulnerabilities that have been deemed necessary to be addressed, are the links to the fixes attached to this issue?
- [ ] For vulnerabilities that have been deemed not necessary to be addressed, is a reason for each of them documented in this issue?
- [ ] The corresponding pull request in this repo has been merged.

## Audit 

Audit file : https://sayfer.io/audits/metamask-snap-audit-report-for-qtum/

Vulnerabilities : 
<img width="755" alt="Capture d’écran 2024-09-03 à 02 39 58" src="https://github.com/user-attachments/assets/13748815-18da-435f-a4f7-87ffd91a4e2d">

List (all of them have been fixed). But I can't find the link to the fixes in the report.

- No Method to Remove Added Networks
- Missing Confirmation Prompt for Exporting Private Keys
- Multiple Unimplemented Methods
- Redundant Code
- Leftover TODO Comments

**Comment by khanti42** [comment]
Still need to check what website the team wants to use, because it was not present in the allowlist request. As the demo uses https://bridge.qtum.net/ I put this for now. I will confirm.

**Comment by khanti42** [comment]
Website confirmed by the team

**Comment by Montoya** [comment]
@khanti42 I think there are no fixes linked in the security audit report because they are low / informational issues and not required to be fixed. This is acceptable.
