### ISSUE TITLE
[Update Snap] Starknet Snap

### ISSUE THREAD

**Issue by khanti42** [MetaMask/snaps-registry#838]
## Checklist

All items in the list below needs to be satisfied.

- [x] Is the summary of the change documented in this ticket: minor bug fix, https://github.com/Consensys/starknet-snap/pull/364
- [x] Has a MetaMask Snaps team member reviewed whether the changes need to be vetted?
- [ ] If there are changes that need to be vetted, attach a description and the relevant fixes/remediations to this issue.
- [ ] The corresponding pull request in this repo has been merged.

**Comment by Montoya** [comment]
Change here: https://github.com/Consensys/starknet-snap/compare/starknet-snap-v2.10.0...starknet-snap-v2.10.1
