### ISSUE TITLE
[Update Snap] XRPL

### ISSUE THREAD

**Issue by khanti42** [MetaMask/snaps-registry#859]
## Checklist

All items in the list below needs to be satisfied.

- [x] Is the summary of the change documented in this ticket?
- [x] Has a MetaMask Snaps team member reviewed whether the changes need to be vetted?
- [ ] If there are changes that need to be vetted, attach a description and the relevant fixes/remediations to this issue.
- [ ] The corresponding pull request in this repo has been merged.

Updating svg logo.

**Comment by Montoya** [comment]
This updates the logo of the Snap to match the screenshots in the registry

**Comment by khanti42** [comment]
There where some small code changes as well, here is the diff shared by the builder: https://github.com/Peersyst/xrpl-snap/pull/108/files
