### ISSUE TITLE
[New Snap] kobosu

### ISSUE THREAD

**Issue by khanti42** [MetaMask/snaps-registry#910]
## Checklist

All items in the list below needs to be satisfied.

- [x] Is the Snap repository publicly accessible and linked in this ticket: https://github.com/DoggyFiOfficial/dogecoin-snap-public
- [x] Is the Snap distributed on [npm](https://www.npmjs.com/) and linked in this ticket: https://www.npmjs.com/package/@doggyfi-official/kobosu
- [x] Has an audit been performed and the audit report attached or linked in this issue ?
- [x] Is a complete list of discovered vulnerabilities from the audit documented in this issue?
- [ ] For vulnerabilities that have been deemed necessary to be addressed, are the links to the fixes attached to this issue?
- [ ] For vulnerabilities that have been deemed not necessary to be addressed, is a reason for each of them documented in this issue?
- [ ] The corresponding pull request in this repo has been merged.

## Audit 

Auditor : Sayfer 
Link : https://sayfer.io/audits/metamask-snap-audit-report-for-doggyfi/

### Security Assessment Findings:

1. **Fees Are Not Displayed to the User** (ID: SAY-01)
   - **Status**: Fixed
   - **Risk**: Medium
   - **Issue**: Users were not shown the transaction fees upfront in the confirmation prompt, leading to a potential breach of trust.
   - **Mitigation**: Fees are now displayed separately in the initial prompt.

2. **Dependencies with Floating Versions** (ID: SAY-02)
   - **Status**: Fixed
   - **Risk**: Low
   - **Issue**: Dependencies were not pinned to exact versions, increasing the risk of supply chain attacks.
   - **Mitigation**: Use of exact versions for all packages is recommended.

3. **Fee Data Not Displayed on Initial Prompt** (ID: SAY-03)
   - **Status**: Acknowledged
   - **Risk**: Low
   - **Issue**: While fees are displayed, they only appear after the initial confirmation, which could lead to a poor UX as users might skip later prompts.
   - **Mitigation**: Fees should be presented in the first prompt.

4. **Development Leftovers** (ID: SAY-04)
   - **Status**: Fixed
   - **Risk**: Informational
   - **Issue**: There were comments and unfinished features in the code that had been overlooked.
   - **Mitigation**: Ensure all known issues are resolved before production.

**Comment by khanti42** [comment]
Team had to make a fix and bumped the version to 0.1.4. 

Reason: There was an erroreous line of code in sendDoginal that was never caught making signing a sendDoginal tx impossible. Builder removed line as your team can see here: https://github.com/DoggyFiOfficial/dogecoin-snap-public/commit/f567664732f4600442b9155cdf2539c4649d2598#diff-7bf51f3994b5de19f663e7e8fb6ecbf37bcd0989f855752ad7214c1210570268L1272

**Comment by khanti42** [comment]
Team had to make an other fix discovered after companion website was live, this is in the following two commits

- edge case related to wallets with a large number of utxos not paginating our API properly.
- additionally, they revised the mintDune / openDune built in functionality to not require the user to know how to shift decimals, and hand decimals properly on mints. 

See commits

- https://github.com/DoggyFiOfficial/dogecoin-snap-public/commit/49ab4c5ad0ad90aa34fe1a1d545796b7d91802cb
- https://github.com/DoggyFiOfficial/dogecoin-snap-public/commit/8d44a8137faa38a365ea3583c6689c684636488a

**Comment by 1CMG** [comment]
When trying to move DOGE from my DoggyFi wallet using the MetaMask snap, I get an error, "cannot read properties of undefined ("reading filter").  Anyone know the cause and resolution?
